source 'https://rubygems.org'

require 'localconfig/config'
branch = LocalConfig.branch
puts "branch: #{branch}"

# gem 'localconfig',
#   git: 'https://github.com/obfusk/rb-localconfig.git',
#   branch: 'master'

# gem 'foo', branch: branch
# gem 'bar', branch: branch
